# Generated by Django 5.0.14 on 2026-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề')),
                ('excerpt', models.TextField(blank=True, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('title', models.CharField(max_length=120, verbose_name='Chức danh')),
                ('about', models.TextField(verbose_name='Giới thiệu')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Số điện thoại')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Hồ sơ',
                'verbose_name_plural': 'Hồ sơ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề dự án')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('technologies', models.CharField(blank=True, help_text='VD: Django, React, PostgreSQL', max_length=200, verbose_name='Công nghệ sử dụng')),
                ('link', models.URLField(blank=True, verbose_name='Link (GitHub/Demo)')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỹ năng')),
                ('level', models.CharField(blank=True, help_text='VD: Beginner, Intermediate, Advanced, Expert', max_length=50, verbose_name='Trình độ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Kỹ năng',
                'verbose_name_plural': 'Kỹ năng',
            },
        ),
    ]
