# Generated by Django 5.0.14 on 2026-05-13 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.PositiveSmallIntegerField(default=5, help_text='Điểm từ 1 đến 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Listening')),
                ('reading', models.PositiveSmallIntegerField(default=5, help_text='Điểm từ 1 đến 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Reading')),
                ('writing', models.PositiveSmallIntegerField(default=5, help_text='Điểm từ 1 đến 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Writing')),
                ('speaking', models.PositiveSmallIntegerField(default=5, help_text='Điểm từ 1 đến 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Speaking')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Điểm IELTS',
                'verbose_name_plural': 'Điểm IELTS',
            },
        ),
    ]
