# Generated by Django 5.0.14 on 2026-05-13 18:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_ieltsscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsscore',
            name='listening',
            field=models.DecimalField(choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9'), '9.0')], decimal_places=1, default=Decimal('5.0'), help_text='Điểm từ 0.0 đến 9.0, bước 0.5', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))], verbose_name='Listening'),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='reading',
            field=models.DecimalField(choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9'), '9.0')], decimal_places=1, default=Decimal('5.0'), help_text='Điểm từ 0.0 đến 9.0, bước 0.5', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))], verbose_name='Reading'),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='speaking',
            field=models.DecimalField(choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9'), '9.0')], decimal_places=1, default=Decimal('5.0'), help_text='Điểm từ 0.0 đến 9.0, bước 0.5', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))], verbose_name='Speaking'),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='writing',
            field=models.DecimalField(choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9'), '9.0')], decimal_places=1, default=Decimal('5.0'), help_text='Điểm từ 0.0 đến 9.0, bước 0.5', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))], verbose_name='Writing'),
        ),
    ]
