# Generated by Django 5.0.14 on 2026-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_ieltsscore_listening_alter_ieltsscore_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Ảnh hồ sơ'),
        ),
    ]
